name : CI
on:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install PortAudio (for Sounddevice)
              run: sudo apt-get update && sudo apt-get install libportaudio2

            - name: Install uv
              uses: astral-sh/setup-uv@v3

            - name: Sync Depedencies
              run: uv sync && uv sync --dev
